### PR TITLE
Add Oracle db support

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/twofactor_webauthn/issues/175

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Table name "oc_twofactor_webauthn_registrations" is too long.

:confetti_ball:

**Comment by nickvergessen** [comment]
Been there, done that. Not a problem at all:
https://github.com/nextcloud/terms_of_service/pull/74/files

1. Remove content of old migration (or as I prefer comment it out, so you still hit it with the search) `lib/Migration/Version1000Date20180503135440.php`
2. Create a new migration which creates a correct DB `lib/Migration/Version1000Date20181122140802.php`
    * In post migration check for old table existance and copy data in that case
4. Add another new migration which drops the old table in case it exists `lib/Migration/Version1000Date20181122141014.php`

**Review by ChristophWurst — COMMENTED** [review]
:+1:

**Review by st3iny — APPROVED** [review]
Tested 3 cases:

1. Install 0.4.0-alpha1 right away.
2. Install 0.3.0 and upgrade without any devices.
3. Install 0.3.0, add devices and then upgrade.

**Pull request merged**
