### PR TITLE
Fix white login icon on white background

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] Requires dropping Nextcloud 24 and older

| Before | After |
|---|---|
| Bildschirmfoto vom 2022-09-16 16-09-26 | Bildschirmfoto vom 2022-09-16 16-09-32 |

cc @nursoda

For https://github.com/nextcloud/twofactor_webauthn/issues/253

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Review by st3iny — COMMENTED** [review]
Looks weird on the dark theme:

image

**Comment by st3iny** [comment]
> > Looks weird on the dark theme:
> 
> Did you test on NC25 beta7(!) ? There, with System set to dark, FX and NC set to follow system, I see this:
> 
> grafik

Yes, I tested on the latest Nextcloud master branch. It works on Chromium because it doesn't follow the system theme. However, on Firefox it follows my dark theme and the icon is dark too. It seems like the "global" theme can't be configured and Nextcloud follows the system theme by default (if supported by the browser).

**PS:** Are you sure that you checked out this branch before testing? It seems that your on another version of the app due to the updated phrasing.

**Review by st3iny — APPROVED** [review]
My dark mode browser extension was buggy. Completely disabled it in the browser settings and suddenly it worked as expected.

**Comment by nursoda** [comment]
@ChristophWurst Most SERVER Theming issues should be be settled by 25.0.2. Not so the twofactor_webauthn icon:

grafik

Please re-open, re-test, and probably revert.

**Pull request merged**
