### PR TITLE
feat(deps): Add Nextcloud 28 support

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by st3iny — APPROVED** [review]
I also adjusted info.xml.

**Comment by st3iny** [comment]
:upside_down_face: 

```

  Problem 1
    - Root composer.json requires nextcloud/ocp dev-master -> satisfiable by nextcloud/ocp[dev-master].
    - nextcloud/ocp dev-master requires psr/container ^2.0.2 -> found psr/container[2.0.2] but the package is fixed to 1.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
  Problem 1
    - Root composer.json requires nextcloud/ocp dev-master -> satisfiable by nextcloud/ocp[dev-master].
    - nextcloud/ocp dev-master requires psr/container ^2.0.2 -> found psr/container[2.0.2] but the package is fixed to 1.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

Let's just force merge this to prevent getting stuck ...

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> et's just force merge this to prevent getting stuck ...

https://github.com/nextcloud/mail/pull/8515 ?

**Comment by st3iny** [comment]
> > et's just force merge this to prevent getting stuck ...
> 
> [nextcloud/mail#8515](https://github.com/nextcloud/mail/pull/8515) ?

https://github.com/nextcloud/twofactor_webauthn/pull/395

**Pull request merged**
